// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// manchester_tx //
// ------------- //

#define manchester_tx_wrap_target 0
#define manchester_tx_wrap 12
#define manchester_tx_pio_version 0

static const uint16_t manchester_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0x6021, //  1: out    x, 1            side 0
    0x0028, //  2: jmp    !x, 8           side 0
    0xe05f, //  3: set    y, 31           side 0
    0x0f84, //  4: jmp    y--, 4          side 0 [15]
    0xf05f, //  5: set    y, 31           side 1
    0x1f86, //  6: jmp    y--, 6          side 1 [15]
    0x100c, //  7: jmp    12              side 1
    0xf05f, //  8: set    y, 31           side 1
    0x1f89, //  9: jmp    y--, 9          side 1 [15]
    0xe05f, // 10: set    y, 31           side 0
    0x0f8b, // 11: jmp    y--, 11         side 0 [15]
    0x00e1, // 12: jmp    !osre, 1        side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program manchester_tx_program = {
    .instructions = manchester_tx_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = manchester_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config manchester_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + manchester_tx_wrap_target, offset + manchester_tx_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void manchester_tx_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = manchester_tx_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin, 1);
    sm_config_set_sideset_pins(&c, pin);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Shift right, NO autopull, threshold 8 bits
    sm_config_set_out_shift(&c, true, false, 8);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

